
events {}

http {
	include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
	
    server {
        listen 80;
        server_name localhost;
	client_max_body_size 20M;
        root /usr/share/nginx/html;
        index index.html;

        # Only serve real files
        location / {
            try_files $uri =404;
        }

        # Block dangerous file types completely
        location ~* \.(php|phar|exe|sh|cgi|pl)$ {
            deny all;
        }

        # Image caching
        location /uploads/ {
			autoindex off;
            expires 30d;
            add_header Cache-Control "public";
        }
    }
}
